name: popover_example
description: iOS/iPadOS Style Popover Example.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  popover:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
